version: '2.1'
volumes:
  bitwarden-config: {}
services:
  bitwarden:
    image: bitwardenrs/server:latest@sha256:77a08166afa041e55a9d5ef05d3cc3dfe1b1f67c77a056d9e4c8b73d0eca1768
    expose:
      - '443'
      - '80'
    network_mode: host
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - 'bitwarden-config:/data'
      - 'bitwarden-config:/ssl'
    environment:
      ROCKET_TLS: '{certs = "/ssl/cert.pem", key = "/ssl/key.pem"}'
      LOG_FILE: '/data/bitwarden.log'
      SIGNUPS_ALLOWED: 'true'

